### ISSUE TITLE
Any chance you could create a nuget package just for loading and saving avif images?

### ISSUE THREAD

**Issue by AnderssonPeter** [0xC0000054/pdn-avif#15]
Any chance you could create a nuget package just for loading and saving avif images? so that we can use avif in other .net products

**Comment by 0xC0000054** [comment]
> Any chance you could create a nuget package just for loading and saving avif images?

I do not plan to.
There are existing libraries such as [libheif](https://github.com/strukturag/libheif) that can load and save AVIF images, with support for additional AVIF decoders and encoders (such as dav1d and rav1e).

A lot of the code in this repository is closely tied to Paint.NET's plugin architecture, and it would be a significant amount of work to adapt it for use with other .NET graphics APIs.
The native code is a custom interface to the AOM decoder and encoder.
