### ISSUE TITLE
ARM64 build of native dll?

### ISSUE THREAD

**Issue by bbowyersmyth** [0xC0000054/pdn-avif#17]
I'm not that familiar with C++ build configurations. Is an ARM64 build of AOM possible?

**Comment by 0xC0000054** [comment]
>  Is an ARM64 build of AOM possible?

According to the [AOM readme](https://aomedia.googlesource.com/aom/+/refs/tags/v2.0.1/README.md) it supports cross-compiling ARM64 builds using a number of compilers, including MinGW-w64 on Windows.
You should be able to modify one of the existing CMake tool-chain files to cross-compile for ARM64 with Visual Studio.

**Comment by rickbrew** [comment]
I've got a used Surface Pro X coming soon, I should be able to test and/or help out on this. Can't release an ARM64 release of PDN until .NET 6 releases around November though. .NET 5 doesn't support WPF on ARM64, but .NET 6 does. (Paint.NET uses WPF's data binding engine)

**Comment by 0xC0000054** [comment]
Closing this issue as the native DLL now has an ARM64 version.
