### ISSUE TITLE
"BuildDate.txt" can be replaced with asterisk versioning

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-avif#2]
I see a pre-build event that generates a BuildDate.txt file using powershell.

If a "build date" is desired, you can actually get the C# compiler to do this automatically:

`[assembly: AssemblyVersion("1.0.*.*")]`

(or maybe you specify `1.0.*` ... not sure which one is correct)

The first * (in the 3rd position, the "Build") will be become the # of days since 2000-01-01. Easy to calculate the build date from that.

The second * (in the 4th position, the "Revision") will be the # of seconds since UTC midnight, divided by 2. Easy enough to calculate the build time from that.

See also `PdnInfo.cs::BuildTimeUtc`

**Comment by rickbrew** [comment]
The real problem is here that building the solution does not work unless you manually create the `Resources` directory. git doesn't seem to include empty directories, and since `BuildDate.txt` isn't committed, you'll always get an error if you clone this repository and try to build it.

```
1>------ Build started: Project: AvifFileType, Configuration: Debug Any CPU ------
1>  Out-File : Could not find a part of the path 'D:\src\github\pdn-avif\src\Resources\BuildDate.txt'.
1>  At line:1 char:48
1>  + ... ring("s") | Out-File 'D:\src\github\pdn-avif\src\Resources\BuildDate. ...
1>  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1>      + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
1>      + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
1>   
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1330,5): error MSB3073: The command "powershell -Command "((Get-Date).ToUniversalTime()).ToString(\"s\") | Out-File 'D:\src\github\pdn-avif\src\Resources\BuildDate.txt'"" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by rickbrew** [comment]
Or, since the build date seems to be used for expiring the plugin, maybe this can just be removed altogether? 🤔

**Comment by 0xC0000054** [comment]
I went with the powershell method as that would have allowed me to use the 3rd digit of the version number as a patch number, matching the [Semantic Versioning](https://semver.org/) standard.
I ended up never using the patch number, so in hindsight I could have used the built-in method.

> Or, since the build date seems to be used for expiring the plugin, maybe this can just be removed altogether? 🤔

I will remove it.
