### ISSUE TITLE
Paint.net 5 - preview of the file size for avif file - wrong calculation (preview e.g. 170 KB - saved file 189 KB)

### ISSUE THREAD

**Issue by JamesPous** [0xC0000054/pdn-avif#21]
I saved a avif file with Paint.net 5 alpha and in the preview window you see the estimated file size of the final picture file.
I tested it with different pictures and all pictures get around 20 KB bigger than the calculation.
Is it possible to show a more precise estimate filesize? That would be nice.

**Comment by 0xC0000054** [comment]
The file size estimate is handled by Paint.NET. You should report this issue in the Paint.NET 5 forum thread for the version you are using.
