### ISSUE TITLE
AvifNative DLLs are enormous

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-avif#4]
These are about 7.5MB each. Is there a way to get these to be a lot smaller?

PDN is currently a 10MB download

**Comment by rickbrew** [comment]
Luckily the download only increases in size by about 2.7MB due to the extremely aggressive LZMA compression that I'm using for the NSIS package

... smaller is still better though, so if there's a way to easily reduce the size of these DLLs, that'd be great.

**Comment by rickbrew** [comment]
paint.net.4.2.11.install.zip is 9,892 KB

paint.net.4.2.12.install.zip (for the build I'm working on) is 12,616 KB with the bundled AvifFileType

**Comment by 0xC0000054** [comment]
Unfortunately, aom is a huge library, even the example decoder/encoder programs are ~7MB (see https://ci.appveyor.com/project/marcomsousa/build-aom/builds/32987143/artifacts).
I could try disabling the aom decoder and switching to [dav1d](https://github.com/videolan/dav1d), but I am not sure how much space that would save.

**Comment by rickbrew** [comment]
I would first experiment with switch the compiler settings to "minimize size", and remove intrinsics, etc. That's what I mean by "easy".

Increasing the download by 2.7MB isn't actually too bad -- once the app is ported to .NET Core the download size will balloon anyway, so it's actually a good idea to slowly increase the size so it's not as much of a shock to the system (percentage wise)

**Comment by rickbrew** [comment]
Alright so even compressing the AVIF plugin files with max settings in 7Zip results in an archive that's only 2607 KB. So, that's pretty darn good.

![image](https://user-images.githubusercontent.com/10873410/82926585-48fedf00-9f34-11ea-982d-b31083ed5b2d.png)

So I'm no longer concerned about this and I don't consider it a blocking issue. Smaller is still better, so if there's something that can be done really easily without compromising performance too much, that'd be nice to discover (and by "easy" I mean compiler switches or #defines).

I'm also guessing that there are AVX2 optimizations that aren't being enabled? It may be possible to add e.g. AvifNative_x64_AVX2.dll. Since almost all of the bits in that DLL will be the same as AvifNative_x64.dll, it will be mostly free from the standpoint of download size. So, feel free to try that out.

**Comment by 0xC0000054** [comment]
> I'm also guessing that there are AVX2 optimizations that aren't being enabled?

The AOM static library is configured to build with AVX2 enabled, though I have no idea if it would perform runtime detection and use it.

**Comment by rickbrew** [comment]
Wait, so `AvifFileType` requires AVX2?

**Comment by 0xC0000054** [comment]
> Wait, so AvifFileType requires AVX2?

After a lot of digging I finally found the code that performs runtime detection for CPU features, the `rtcd` files / project.
The encoder will only use AVX2 if the current CPU supports it.
