### ISSUE TITLE
Should FileType's name be "AVIF" or "AV1" ?

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-avif#5]
The built-in AV1FileType (PDN v4.2.11 and earlier) calls it "AV1" with, of course, *.avif as the extensions.

AvifFileType.dll (plugin) calls it "AVIF".

Should it be "AV1", "AVIF", or even "AV1 (AVIF)" ?

**Comment by 0xC0000054** [comment]
I will change it to "AV1 (AVIF)" for the next release.

I am currently trying to switch the decoder to use dav1d, which should improve the decoding speed and memory usage.
Hopefully it will also reduce the DLL sizes by a few hundred KB.
