### ISSUE TITLE
Update readme after bundling

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-avif#6]
Mention that it's now integrated, similar to DDS and WebP's readme changes

It doesn't need the instructions for setting the AppSetting that disables the built-in FileType

**Comment by rickbrew** [comment]
*bump* :)

**Comment by 0xC0000054** [comment]
> _bump_ :)

I added the Paint.NET 4.2.14 bundling note.

I am waiting until after the release of 4.2.14 to remove the registry instructions, that way users can still install the plugin on 4.2.13.
