### ISSUE TITLE
Consider changing default compression speed to 'Fast'

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-avif#9]
Saving with "Normal" is _very_ slow, even on my Ryzen 3950X. Obviously due to aom's current implementation.

What do you think about changing the default to "Fast" ? (and potentially renaming 'Normal' since it's no longer 'normal')

**Comment by 0xC0000054** [comment]
> What do you think about changing the default to "Fast" ?

I would be fine with that.

> (and potentially renaming 'Normal' since it's no longer 'normal')

I will rename it to 'Medium'.
